-- KioskNotifier: Oracle DDL
-- 진료실 매핑 테이블
CREATE TABLE PC_ROOM_MAP (
    PC_ID        VARCHAR2(64)  NOT NULL,
    HOSTNAME     VARCHAR2(128),
    IP_ADDRESS   VARCHAR2(64),
    ROOM_CD      VARCHAR2(32)  NOT NULL,
    ROOM_NM      VARCHAR2(128),
    DOCTOR_NM    VARCHAR2(64),
    SOUND_YN     CHAR(1)       DEFAULT 'Y' NOT NULL,
    UPDATED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PC_ROOM_MAP PRIMARY KEY (PC_ID)
);
CREATE INDEX IX_PC_ROOM_MAP_HOST ON PC_ROOM_MAP(HOSTNAME);
CREATE INDEX IX_PC_ROOM_MAP_IP   ON PC_ROOM_MAP(IP_ADDRESS);
CREATE INDEX IX_PC_ROOM_MAP_ROOM ON PC_ROOM_MAP(ROOM_CD);

-- 알림 큐 테이블
CREATE TABLE NOTIFY_QUEUE (
    EVENT_ID      VARCHAR2(64)  NOT NULL,
    ROOM_CD       VARCHAR2(32)  NOT NULL,
    MSG_TYPE      VARCHAR2(16)  DEFAULT 'ARRIVAL' NOT NULL,
    PATIENT_NO    VARCHAR2(32),
    PATIENT_NM    VARCHAR2(64),
    DOCTOR_NM     VARCHAR2(64),
    MEMO          VARCHAR2(400),
    CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    DELIVERED_AT  TIMESTAMP,
    READ_AT       TIMESTAMP,
    CONSTRAINT PK_NOTIFY_QUEUE PRIMARY KEY (EVENT_ID)
);
CREATE INDEX IX_NOTIFY_QUEUE_ROOM_TIME ON NOTIFY_QUEUE(ROOM_CD, CREATED_AT);
CREATE INDEX IX_NOTIFY_QUEUE_UNDELIVERED ON NOTIFY_QUEUE(ROOM_CD, DELIVERED_AT);
